/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2020-09-23 02:47:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class review_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Java/lms_system-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LMS_PROJECT/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/views/user/../include/corejs.jsp", Long.valueOf(1600671055000L));
    _jspx_dependants.put("/WEB-INF/views/user/../include/footer.jsp", Long.valueOf(1600671055000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Java/lms_system-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LMS_PROJECT/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/views/user/../include/sidebar.jsp", Long.valueOf(1600671055000L));
    _jspx_dependants.put("/WEB-INF/views/user/../include/topbar.jsp", Long.valueOf(1600671055000L));
    _jspx_dependants.put("/WEB-INF/views/user/../include/head.jsp", Long.valueOf(1600671055000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Java/lms_system-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LMS_PROJECT/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1598927236110L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t");
      out.write("\n");
      out.write("\n");
      out.write(" <title>weLEarn - 배우고! 익히고!</title>\n");
      out.write(" <!-- Required meta tags -->\n");
      out.write(" <meta charset=\"utf-8\">\n");
      out.write(" <meta content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\" name=\"viewport\" />\n");
      out.write(" <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write(" <!--     Fonts and icons     -->\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\n");
      out.write(" <!-- Material Kit CSS -->\n");
      out.write(" <link href=\"/resources/assets/css/material-dashboard.css?v=2.1.0\" rel=\"stylesheet\" />\n");
      out.write(" <!-- include libraries(jQuery) -->\n");
      out.write(" <script src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"dark-edition\">\n");
      out.write(" <div class=\"wrapper \">\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("  <div class=\"sidebar\" data-color=\"purple\" data-background-color=\"black\" data-image=\"/resources/assets/img/sidebar-2.jpg\">\n");
      out.write("      <div class=\"logo\"><a href=\"/home\" class=\"simple-text logo-normal\">\n");
      out.write("        \t  ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        \t  ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </a></div>\n");
      out.write("      <div class=\"sidebar-wrapper\">\n");
      out.write("        <ul class=\"nav\">\n");
      out.write("          <li class=\"nav-item study-t\">\n");
      out.write("            <a class=\"nav-link\" href=\"/user/study\">\n");
      out.write("              <i class=\"material-icons\">edit</i>\n");
      out.write("              <p>학습하기</p>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item review-t\">\n");
      out.write("            <a class=\"nav-link\" href=\"/user/review\">\n");
      out.write("              <i class=\"material-icons\">psychology</i>\n");
      out.write("              <p>복습하기</p>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item ques-t\">\n");
      out.write("            <a class=\"nav-link\" href=\"/user/testing\">\n");
      out.write("              <i class=\"material-icons\">rate_review</i>\n");
      out.write("              <p>모의고사</p>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dash-t\">\n");
      out.write("            <a class=\"nav-link\" href=\"/user/status\">\n");
      out.write("              <i class=\"material-icons\">dashboard</i>\n");
      out.write("              <p>학습현황</p>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item m-ques-t\">\n");
      out.write("            <a class=\"nav-link\" href=\"/user/demands\">\n");
      out.write("              <i class=\"material-icons\">support_agent</i>\n");
      out.write("              <p>관리자에게 문의</p>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item alert-t\">\n");
      out.write("            <a class=\"nav-link\" href=\"\">\n");
      out.write("              <i class=\"material-icons\">notifications</i>\n");
      out.write("              <p>알리미</p>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>");
      out.write("\n");
      out.write("    <div class=\"main-panel\">\n");
      out.write("      ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav\n");
      out.write("\tclass=\"navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top \"\n");
      out.write("\tid=\"navigation-example\">\n");
      out.write("\t<div class=\"container-fluid\">\n");
      out.write("\t\t<div class=\"navbar-wrapper\">\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"javascript:void(0)\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("\t\t\taria-controls=\"navigation-index\" aria-expanded=\"false\"\n");
      out.write("\t\t\taria-label=\"Toggle navigation\" data-target=\"#navigation-example\">\n");
      out.write("\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
      out.write("\t\t\t\tclass=\"navbar-toggler-icon icon-bar\"></span> <span\n");
      out.write("\t\t\t\tclass=\"navbar-toggler-icon icon-bar\"></span> <span\n");
      out.write("\t\t\t\tclass=\"navbar-toggler-icon icon-bar\"></span>\n");
      out.write("\t\t</button>\n");
      out.write("\t\t<div class=\"collapse navbar-collapse justify-content-end\">\n");
      out.write("\t\t\t<ul class=\"navbar-nav\">\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a class=\"nav-link\" href=\"javscript:void(0)\" id=\"navbarDropdownMenuLink\"\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("\t\t\t\t\t\t<i class=\"material-icons\">person</i>\n");
      out.write("\t\t\t\t\t\t<p class=\"d-lg-none d-md-block\">사용자</p>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"javascript:void(0)\">\n");
      out.write("\t\t\t\t\t<i class=\"material-icons\">notifications</i>\n");
      out.write("\t\t\t\t\t<span class=\"notification\">5</span>\n");
      out.write("\t\t\t\t\t<p class=\"d-lg-none d-md-block\">알림</p>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("      <div class=\"content\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("          <!-- your content here -->\n");
      out.write("            <div id=\"reviewBoard\" class=\"col-md-12\">\n");
      out.write("            \t\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      ");
      out.write("\n");
      out.write("\n");
      out.write("    <footer class=\"footer\" data-background-color=\"black\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <nav class=\"float-left\">\n");
      out.write("        <ul>\n");
      out.write("       \t  <li>\n");
      out.write("            <a href=\"/home\">\n");
      out.write("             \t Home\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"/admin\">\n");
      out.write("             \t Manager\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </nav>\n");
      out.write("      <div class=\"copyright float-right\">\n");
      out.write("        &copy;\n");
      out.write("        <script>\n");
      out.write("          document.write(new Date().getFullYear())\n");
      out.write("        </script>, made with <i class=\"material-icons\">favorite</i> by\n");
      out.write("        <a href=\"https://www.creative-tim.com/\" target=\"_blank\">잇플</a> for a better learn.\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </footer>");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("  \t  var index = 0;\n");
      out.write("  \t  var list = JSON.parse('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jsonList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("  \t  \n");
      out.write("      function addAlert(){\n");
      out.write("    \tlet boardDiv = document.getElementById('reviewBoard');\n");
      out.write("    \t\n");
      out.write("    \tlet div = document.createElement(\"div\");\n");
      out.write("    \t\n");
      out.write("    \tif(list[index].memoryRate >= 60){\n");
      out.write("\t    \tdiv.classList.add(\"alert\",\"alert-success\");\n");
      out.write("    \t}else if(list[index].memoryRate >= 30){\n");
      out.write("    \t\tdiv.classList.add(\"alert\",\"alert-warning\");\n");
      out.write("    \t}else{\n");
      out.write("    \t\tdiv.classList.add(\"alert\",\"alert-danger\");\n");
      out.write("    \t}    \t\n");
      out.write("\t    \tlet button = document.createElement(\"button\");\n");
      out.write("\t    \tbutton.setAttribute('type', 'button');\n");
      out.write("\t    \tbutton.setAttribute('class', 'close');\n");
      out.write("\t    \tbutton.setAttribute('data-dismiss', 'alert');\n");
      out.write("\t    \tbutton.setAttribute('aria-label', 'Close');\n");
      out.write("\t    \tbutton.setAttribute('aria-label', 'Close');\n");
      out.write("\t    \tbutton.addEventListener(\"click\", addAlert);\n");
      out.write("\t    \t\n");
      out.write("\t\t    \tlet i = document.createElement(\"i\");\n");
      out.write("\t\t    \ti.setAttribute('class', 'material-icons');\n");
      out.write("\t\t    \ti.innerText = 'close';\n");
      out.write("\t\t    \n");
      out.write("\t\t    button.appendChild(i);\t\n");
      out.write("\t    \t\n");
      out.write("\t    \tlet span = document.createElement(\"span\");\n");
      out.write("\t    \t\n");
      out.write("\t\t    \tlet a = document.createElement(\"a\");\n");
      out.write("\t\t    \ta.setAttribute('href', '/user/review/hard?stuCode='+list[index].stuCode);\n");
      out.write("\t\t    \ta.innerHTML = list[index].title + \"&nbsp;&nbsp;&nbsp;&nbsp;\";\n");
      out.write("\t\t    \t\n");
      out.write("\t\t    \tlet b = document.createElement(\"b\");\t\n");
      out.write("\t\t    \tb.innerHTML = \"기억률 : \" + list[index].memoryRate.toFixed(1) +\"% &nbsp;&nbsp;&nbsp;&nbsp;\" + list[index].elapsedTime + \"분 전에 학습 &nbsp;&nbsp;&nbsp;&nbsp; [\" + list[index].coName +\"]\";\n");
      out.write("\t\t    \n");
      out.write("\t\t    span.appendChild(a);\n");
      out.write("\t\t    span.appendChild(b);\n");
      out.write("\t    \t\n");
      out.write("\t    \tdiv.appendChild(button);\n");
      out.write("\t    \tdiv.appendChild(span);\n");
      out.write("    \tboardDiv.appendChild(div);\n");
      out.write("    \tif(list.length-1 > index) {\n");
      out.write("    \t\tindex = index + 1;\n");
      out.write("    \t}else {\n");
      out.write("    \t\tindex = 0;\n");
      out.write("    \t}\n");
      out.write("   \t  };\n");
      out.write("      \n");
      out.write("      function init(){\n");
      out.write("  \t\t  let max = list.length > 10 ? 10: list.length;\n");
      out.write("  \t\t  for(i=0; i < max ; i++){\n");
      out.write("  \t\t\t addAlert();\n");
      out.write("   \t\t  }\n");
      out.write("  \t  };\n");
      out.write("      \n");
      out.write("      init();\n");
      out.write("      \n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--   Core JS Files   -->\n");
      out.write("\n");
      out.write("  <script src=\"/resources/assets/js/core/popper.min.js\"></script>\n");
      out.write("  <script src=\"/resources/assets/js/core/bootstrap-material-design.min.js\"></script>\n");
      out.write("  <script src=\"https://unpkg.com/default-passive-events\"></script>\n");
      out.write("  <script src=\"/resources/assets/js/plugins/perfect-scrollbar.jquery.min.js\"></script>\n");
      out.write("  <!-- Place this tag in your head or just before your close body tag. -->\n");
      out.write("  <script async defer src=\"https://buttons.github.io/buttons.js\"></script>\n");
      out.write("  <!--  Google Maps Plugin    -->\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE\"></script>\n");
      out.write("  <!-- Chartist JS -->\n");
      out.write("  <script src=\"/resources/assets/js/plugins/chartist.min.js\"></script>\n");
      out.write("  <!--  Notifications Plugin    -->\n");
      out.write("  <script src=\"/resources/assets/js/plugins/bootstrap-notify.js\"></script>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("  <!-- 썸머노트와는 충돌 됨 ... -->\n");
      out.write("  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc   -->\n");
      out.write("  <script src=\"/resources/assets/js/material-dashboard.js?v=2.1.0\"></script> \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Material Dashboard DEMO methods, don't include it in your project! -->\n");
      out.write("  <script src=\"/resources/assets/demo/demo.js\"></script>\n");
      out.write("  <script>\n");
      out.write("    $(document).ready(function() {\n");
      out.write("      $().ready(function() {\n");
      out.write("        $sidebar = $('.sidebar');\n");
      out.write("\n");
      out.write("        $sidebar_img_container = $sidebar.find('.sidebar-background');\n");
      out.write("\n");
      out.write("        $full_page = $('.full-page');\n");
      out.write("\n");
      out.write("        $sidebar_responsive = $('body > .navbar-collapse');\n");
      out.write("\n");
      out.write("        window_width = $(window).width();\n");
      out.write("\n");
      out.write("        $('.fixed-plugin a').click(function(event) {\n");
      out.write("          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active\n");
      out.write("          if ($(this).hasClass('switch-trigger')) {\n");
      out.write("            if (event.stopPropagation) {\n");
      out.write("              event.stopPropagation();\n");
      out.write("            } else if (window.event) {\n");
      out.write("              window.event.cancelBubble = true;\n");
      out.write("            }\n");
      out.write("          }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $('.fixed-plugin .active-color span').click(function() {\n");
      out.write("          $full_page_background = $('.full-page-background');\n");
      out.write("\n");
      out.write("          $(this).siblings().removeClass('active');\n");
      out.write("          $(this).addClass('active');\n");
      out.write("\n");
      out.write("          var new_color = $(this).data('color');\n");
      out.write("\n");
      out.write("          if ($sidebar.length != 0) {\n");
      out.write("            $sidebar.attr('data-color', new_color);\n");
      out.write("          }\n");
      out.write("\n");
      out.write("          if ($full_page.length != 0) {\n");
      out.write("            $full_page.attr('filter-color', new_color);\n");
      out.write("          }\n");
      out.write("\n");
      out.write("          if ($sidebar_responsive.length != 0) {\n");
      out.write("            $sidebar_responsive.attr('data-color', new_color);\n");
      out.write("          }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $('.fixed-plugin .background-color .badge').click(function() {\n");
      out.write("          $(this).siblings().removeClass('active');\n");
      out.write("          $(this).addClass('active');\n");
      out.write("\n");
      out.write("          var new_color = $(this).data('background-color');\n");
      out.write("\n");
      out.write("          if ($sidebar.length != 0) {\n");
      out.write("            $sidebar.attr('data-background-color', new_color);\n");
      out.write("          }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $('.fixed-plugin .img-holder').click(function() {\n");
      out.write("          $full_page_background = $('.full-page-background');\n");
      out.write("\n");
      out.write("          $(this).parent('li').siblings().removeClass('active');\n");
      out.write("          $(this).parent('li').addClass('active');\n");
      out.write("\n");
      out.write("\n");
      out.write("          var new_image = $(this).find(\"img\").attr('src');\n");
      out.write("\n");
      out.write("          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {\n");
      out.write("            $sidebar_img_container.fadeOut('fast', function() {\n");
      out.write("              $sidebar_img_container.css('background-image', 'url(\"' + new_image + '\")');\n");
      out.write("              $sidebar_img_container.fadeIn('fast');\n");
      out.write("            });\n");
      out.write("          }\n");
      out.write("\n");
      out.write("          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {\n");
      out.write("            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');\n");
      out.write("\n");
      out.write("            $full_page_background.fadeOut('fast', function() {\n");
      out.write("              $full_page_background.css('background-image', 'url(\"' + new_image_full_page + '\")');\n");
      out.write("              $full_page_background.fadeIn('fast');\n");
      out.write("            });\n");
      out.write("          }\n");
      out.write("\n");
      out.write("          if ($('.switch-sidebar-image input:checked').length == 0) {\n");
      out.write("            var new_image = $('.fixed-plugin li.active .img-holder').find(\"img\").attr('src');\n");
      out.write("            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');\n");
      out.write("\n");
      out.write("            $sidebar_img_container.css('background-image', 'url(\"' + new_image + '\")');\n");
      out.write("            $full_page_background.css('background-image', 'url(\"' + new_image_full_page + '\")');\n");
      out.write("          }\n");
      out.write("\n");
      out.write("          if ($sidebar_responsive.length != 0) {\n");
      out.write("            $sidebar_responsive.css('background-image', 'url(\"' + new_image + '\")');\n");
      out.write("          }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $('.switch-sidebar-image input').change(function() {\n");
      out.write("          $full_page_background = $('.full-page-background');\n");
      out.write("\n");
      out.write("          $input = $(this);\n");
      out.write("\n");
      out.write("          if ($input.is(':checked')) {\n");
      out.write("            if ($sidebar_img_container.length != 0) {\n");
      out.write("              $sidebar_img_container.fadeIn('fast');\n");
      out.write("              $sidebar.attr('data-image', '#');\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            if ($full_page_background.length != 0) {\n");
      out.write("              $full_page_background.fadeIn('fast');\n");
      out.write("              $full_page.attr('data-image', '#');\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            background_image = true;\n");
      out.write("          } else {\n");
      out.write("            if ($sidebar_img_container.length != 0) {\n");
      out.write("              $sidebar.removeAttr('data-image');\n");
      out.write("              $sidebar_img_container.fadeOut('fast');\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            if ($full_page_background.length != 0) {\n");
      out.write("              $full_page.removeAttr('data-image', '#');\n");
      out.write("              $full_page_background.fadeOut('fast');\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            background_image = false;\n");
      out.write("          }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $('.switch-sidebar-mini input').change(function() {\n");
      out.write("          $body = $('body');\n");
      out.write("\n");
      out.write("          $input = $(this);\n");
      out.write("\n");
      out.write("          if (md.misc.sidebar_mini_active == true) {\n");
      out.write("            $('body').removeClass('sidebar-mini');\n");
      out.write("            md.misc.sidebar_mini_active = false;\n");
      out.write("\n");
      out.write("            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();\n");
      out.write("\n");
      out.write("          } else {\n");
      out.write("\n");
      out.write("            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');\n");
      out.write("\n");
      out.write("            setTimeout(function() {\n");
      out.write("              $('body').addClass('sidebar-mini');\n");
      out.write("\n");
      out.write("              md.misc.sidebar_mini_active = true;\n");
      out.write("            }, 300);\n");
      out.write("          }\n");
      out.write("\n");
      out.write("          // we simulate the window Resize so the charts will get updated in realtime.\n");
      out.write("          var simulateWindowResize = setInterval(function() {\n");
      out.write("            window.dispatchEvent(new Event('resize'));\n");
      out.write("          }, 180);\n");
      out.write("\n");
      out.write("          // we stop the simulation of Window Resize after the animations are completed\n");
      out.write("          setTimeout(function() {\n");
      out.write("            clearInterval(simulateWindowResize);\n");
      out.write("          }, 1000);\n");
      out.write("\n");
      out.write("        });\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    function init(){\n");
      out.write("    \tlet selectTitle = \".");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${select_t}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("    \tif(selectTitle!=\".\"){\n");
      out.write("\t    \tlet menu = document.querySelector(selectTitle);\n");
      out.write("\t    \tmenu.classList.add(\"active\");\n");
      out.write("    \t}\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    init();\n");
      out.write("  </script>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/user/../include/sidebar.jsp(6,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(' ');
          out.write('\'');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("' 님 안녕하세요! ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/user/../include/sidebar.jsp(7,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" Welcome Here!");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/user/../include/topbar.jsp(28,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"navbarDropdownMenuLink\">\n");
          out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/member/loginform\">로그인</a> \n");
          out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/member/joinform\">회원가입</a>\n");
          out.write("\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/user/../include/topbar.jsp(34,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"navbarDropdownMenuLink\">\n");
          out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/member/logout\">로그아웃</a>\n");
          out.write("\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
